services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mcenter.wsgi --bind 0.0.0.0:8000 --access-logfile '-'
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      NAME_DATABASE: ${NAME_DATABASE}
      USER_DATABASE: ${USER_DATABASE}
      HOST: ${HOST}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE}
      PORT: ${PORT}
  db:
    image: postgres:18.2-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NAME_DATABASE}
      POSTGRES_USER: ${USER_DATABASE}
      POSTGRES_PASSWORD: ${PASSWORD_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    
volumes:
  postgres_data: